# Generated by Django 5.2.12 on 2026-03-31 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [

    ]

    operations = [

    ]
