# Generated by Django 5.2.12 on 2026-03-31 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [

    ]

    operations = [

    ]
