# Generated by Django 5.2.12 on 2026-03-31 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_create_pets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='slug',
        ),
    ]
