# Generated by Django 5.2.12 on 2026-03-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_remove_pet_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='slug',
            field=models.SlugField(default='null', unique=True),
            preserve_default=False,
        ),
    ]
